# include the base config like wifi and logging
<<: !include ../include-base.yaml.snipped
<<: !include ../include-esp32.yaml.snipped

substitutions:
  name: poc-esp32
  id: poc_esp
  comment: "ESP Poc"

esphome:
  name: ${name}

packages:
  cam: !include 
    file: ../common/cqrobot-multi-point-photoelectric-liquid-level.yaml

# # http://www.cqrobot.wiki/index.php/Contact_Multi-point_Photoelectric_Liquid_Level_Sensor_SKU:_CQRSENYW003
# sensor:
#   - platform: pulse_meter
#     pin:
#       number: GPIO15
#     name: "Water Level"
#     accuracy_decimals: 0
#     unit_of_measurement: lvl
#     icon: mdi:watering-can
#     filters:
#       - multiply: 0.01
#       - round: 0
#       - round_to_multiple_of: 10
#       - calibrate_linear:
#           method: exact
#           datapoints:
#             - 10 -> 0
#             - 30 -> 1
#             - 60 -> 2
#             - 120 -> 3
#             - 240 -> 4
