# include the base config like wifi and logging


substitutions:
  name: gosund-sp111-05
  id: gosund_sp111_05
  comment: "playground plug"


packages:
  plug: !include 
    file: common/gosund-sp111.yaml
  intervall: !include 
    file: common/switch-intervall.yaml