# include the base config like wifi and logging
<<: !include ./include-base.yaml.snipped
<<: !include ./include-esp32.yaml.snipped
<<: !include ./include-esp32-i2c.yaml.snipped

substitutions:
  name: keeper-box-02
  id: keeper_box_02


esphome:
  name: ${name}

external_components:
  - source: ./my_components
    components: [ somose ]

binary_sensor:
  # https://esphome.io/components/binary_sensor/status.html
  - platform: status
    name: "${name} Status"
    id: ${id}_status


tca9548a:
  - address: 0x70
    id: multiplex0
    i2c_id: bus_a
    channels:
    #   - bus_id: multiplex0channel2
    #     channel: 2
      # - bus_id: multiplex0channel3
        # channel: 3
    #   - bus_id: multiplex0channel4
    #     channel: 4
      # - bus_id: multiplex0channel5
      #   channel: 5
    #   - bus_id: multiplex0channel6
    #     channel: 6
      - bus_id: multiplex0channel7
        channel: 2      


sensor:
#   - platform: somose
#     address: 0x55
#     update_interval: 15s
#     i2c_id: multiplex0channel2
#     temperature:
#         name: "${id}_2_temperature"
#         unit_of_measurement: °C
#     moisture:
#         name: "${id}_2_moisture"
#         unit_of_measurement: '%'
  # - platform: somose
  #   address: 0x55
  #   update_interval: 15s
  #   i2c_id: multiplex0channel3
  #   temperature:
  #       name: "${id}_3_temperature"
  #       unit_of_measurement: °C
  #   moisture:
  #       name: "${id}_3_moisture"
  #       unit_of_measurement: '%'
#   - platform: somose
#     address: 0x55
#     update_interval: 15s
#     i2c_id: multiplex0channel4
#     temperature:
#         name: "${id}_4_temperature"
#         unit_of_measurement: °C
#     moisture:
#         name: "${id}_4_moisture"
#         unit_of_measurement: '%'        
  # - platform: somose
  #   address: 0x55
  #   update_interval: 15s
  #   i2c_id: multiplex0channel5
  #   temperature:
  #       name: "${id}_5_temperature"
  #       unit_of_measurement: °C
  #   moisture:
  #       name: "${id}_5_moisture"
  #       unit_of_measurement: '%'

#   - platform: somose
#     address: 0x55
#     update_interval: 15s
#     i2c_id: multiplex0channel6
#     temperature:
#         name: "${id}_6_temperature"
#         unit_of_measurement: °C
#     moisture:
#         name: "${id}_6_moisture"
#         unit_of_measurement: '%'
  - platform: somose
    address: 0x55
    update_interval: 15s
    i2c_id: multiplex0channel7
    temperature:
        name: "${id}_7_temperature"
        unit_of_measurement: °C
    moisture:
        name: "${id}_7_moisture"
        unit_of_measurement: '%'        