# include the base config like wifi and logging
<<: !include-base base.yaml

esphome:
  name: livingroom

# https://esphome.io/devices/nodemcu_esp8266.html
esp8266:
  board: nodemcu

binary_sensor:
  # https://esphome.io/components/binary_sensor/status.html
  - platform: status
    name: "livingroom Status"

sensor:
  # https://esphome.io/components/sensor/dht.html?highlight=dht
  - platform: dht
    pin: D2
    model: AM2302
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
