# include the base config like wifi and logging
<<: !include base.yaml

esphome:
  name: livingroom
  platform: ESP8266
  board: nodemcuv2

#esp32_ble_tracker:
sensor:
  - platform: dht
    pin: D2
    model: AM2302
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
