site_name: ESPHome
theme:
  name: 'material'
  features:
    - content.code.copy
    - navigation.indexes

  section_page_name: index
#docs_dir: .
repo_name: 'nolte/esphome-configs'
repo_url: 'https://github.com/nolte/esphome-configs'
docs_dir: docs/
plugins:
  - include-markdown
markdown_extensions:
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.highlight:
  - toc:
      permalink: True
