# include the base config like wifi and logging

substitutions:
  name: nous-a1t-06
  id: nous_a1t_06
  comment: "POC mother tents"
  restore_mode: ALWAYS_OFF

packages:
  nous: !include 
    file: common/nous-a1t.yaml
  intervall: !include 
    file: common/switch-intervall.yaml
