substitutions:
  name: nous-a1t-04
  id: nous_a1t_04
  comment: "Box02 Pump"
  restore_mode: ALWAYS_OFF

packages:
  plug: !include 
    file: common/nous-a1t.yaml
  intervall: !include 
    file: common/switch-intervall.yaml


