substitutions:
  name: nous-a1t-04
  id: nous_a1t_04
  comment: "Box Mother Pump"
  

packages:
  plug: !include 
    file: common/nous-a1t.yaml
    vars:
      restore_mode: ALWAYS_OFF
  intervall: !include 
    file: common/switch-intervall.yaml


