---
version: '3'

tasks:
  default:
    cmds:
    - task -l
    silent: true

  run:
    # vars:
    #   DEVICE_FILE: cam-03.yaml
    cmds:
    - | 
      docker run \
          --rm --privileged \
          -v "${PWD}":/config \
          -e WIFI_DOMAIN=".fritz.box" \
          -e WIFI_SSID="$(pass network/wifi/ssid)" \
          -e WIFI_PASSWORD="$(pass network/wifi/password)" \
          -e WIFI_FALLBACK_PASSWORD="$(pass network/wifi/password)" \
          -e MQTT_ENDPOINT="192.168.178.66" \
          -e MQTT_PORT="31883" \
          -e MQTT_USERNAME="esphome" \
          -e MQTT_PASSWORD="notset" \
          -e TZ="Europe/Berlin" \
          --device=/dev/ttyUSB0 \
          -it ghcr.io/esphome/esphome run {{.DEVICE_FILE}}