---
version: '3'

vars:
  PYTHON_VENVS_BASEDIR: ~/.venvs/
  TASK_COLLECTION_BASE: https://raw.githubusercontent.com/nolte/taskfiles/develop/src

includes:
  mkdocs: "{{.TASK_COLLECTION_BASE}}/taskfile-include-mkdocs.yaml"
  esphome: ./.taskfiles/Taskfile_esphome.yml

tasks:
  default:
    cmds:
    - task -l
    silent: true

