# include the base config like wifi and logging
<<: !include ../include-base.yaml
<<: !include ../include-esp32.yaml
<<: !include ./poc.yaml
esphome:
  name: ${name}

sensor:
  # https://esphome.io/components/sensor/dht.html?highlight=dht
#   - platform: dht
#     pin: GPIO23 #GPIO5
#     temperature:
#       name: "${friendly_name_temp} DHT11"
#       id: ${id}_temperature_dht11
#     humidity:
#       name: "${friendly_name_humidity} DHT11"
#       id: ${id}_humidity_dht11
#     model: DHT11
#     update_interval: 60s

  - platform: dht
    pin: GPIO22
    # model: AM2302
    
    temperature:
      name: "${friendly_name_temp} DHT22"
      id: ${id}_temperature_dht22
    humidity:
      name: "${friendly_name_humidity} DHT22"
      id: ${id}_humidity_dht22
    update_interval: 60s
