# include the base config like wifi and logging
substitutions:
  name: box-seed-01
  id: box_seed_01
  comment: "Setzling Box"

packages:
  plug: !include 
    file: common/esp32-az-delivery.yaml
  base: !include 
    file: ./common/base.yaml
    vars:
      project_name: "Setzling_Box_01"
      project_version: "ESP-111" 

  intervall: !include 
    file: common/sensor/sht3xd.yaml
