substitutions:
  name: cam-07
  id: cam_07
  comment: "Sourdough 01 CAM 01"

packages:
  cam: !include 
    file: common/esp32-cam-mb.yaml

sensor:
  - platform: vl53l0x
    name: "${name}_ Distance"
    id: "${id}_distance"
    address: 0x29
    update_interval: 10s
    long_range: true

  - platform: scd30
    # i2c_id: multiplex0channel7
    #id: ${id}
    co2:
      name: "${name} CO2"
      accuracy_decimals: 1
      id: ${id}_co2
    temperature:
      name: "${name} Temperature"
      accuracy_decimals: 2
      id: ${id}_Temperature
    humidity:
      name: "${name} Humidity"
      accuracy_decimals: 1
      id: ${id}_Humidity
    temperature_offset: 1.5 °C
    address: 0x61
    update_interval: 15s

i2c:
  sda: GPIO14
  scl: GPIO15
  scan: true
  id: bus_a