# include the base config like wifi and logging


substitutions:
  name: gosund-sp111-06
  id: gosund_sp111_06
  comment: "Box2 Air"


packages:
  plug: !include 
    file: common/gosund-sp111.yaml
    vars:
      restore_mode: ALWAYS_ON

