substitutions:
  comment: "Circulation pump Box Mother"
  name: nous-a1t-01
  id: nous_a1t_01

packages:
  plug: !include 
    file: common/nous-a1t.yaml
    vars:
      restore_mode: RESTORE_DEFAULT_OFF