# include the base config like wifi and logging

substitutions:
  name: nous-a1t-06
  id: nous_a1t_06
  comment: "Lamp Box 01"
  time_start: 07:00:00
  time_end: 01:00:00

packages:
  nous: !include 
    file: common/nous-a1t.yaml
    vars:
      restore_mode: ALWAYS_OFF

  duration: !include 
    file: common/active-duration.yaml
    vars:
      time_start: ${time_start}
      time_end: ${time_end}
