on:
  release:
    types: [published]

jobs:
  refresh_presentation_branch:
    uses: nolte/gh-plumbing/.github/workflows/reusable-release-cd-refresh-master.yml@80cb5ebb91a3b49126729de31b1037f11c34b5cd # v2.2.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      target_branch: master
    permissions:
      contents: write
