on:
  release:
    types: [published]

jobs:
  refresh_presentation_branch:
    uses: nolte/gh-plumbing/.github/workflows/reusable-release-cd-refresh-master.yml@d51e51ec3ec17ceea09fe9eb40ac00857b6fa1be # v2.0.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      target_branch: master
    permissions:
      contents: write
