on:
  release:
    types: [published]

jobs:
  publish_docs:
    uses: nolte/gh-plumbing/.github/workflows/reusable-mkdocs.yaml@3fccbb333146cd2a65902afd7394db870ae6a978 # v2.1.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      id-token: write
      pages: write
    concurrency:
      cancel-in-progress: true
      group: "pages"
