on:
  release:
    types: [published]

jobs:
  refresh_presentation_branch:
    uses: nolte/gh-plumbing/.github/workflows/reusable-release-cd-refresh-master.yml@3fccbb333146cd2a65902afd7394db870ae6a978 # v2.1.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      target_branch: master
    permissions:
      contents: write
