name: Spelling Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  spelling:
    uses: nolte/gh-plumbing/.github/workflows/reusable-spelling-vale.yaml@d51e51ec3ec17ceea09fe9eb40ac00857b6fa1be # v2.0.0
