name: Spelling Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  spelling:
    uses: nolte/gh-plumbing/.github/workflows/reusable-spelling-vale.yaml@80cb5ebb91a3b49126729de31b1037f11c34b5cd # v2.2.0
